### ISSUE TITLE
How to solve the CORS problem？

### ISSUE THREAD

**Issue by JiangLongLiu** [jjaychen1e/logseq-plugin-image-uploader#5]
OS: WIN64
logseq: 0.5.8

![image](https://user-images.githubusercontent.com/7019907/148935279-e5a0e777-80f5-4d8c-b4e8-77a6f231db56.png)

![g](https://user-images.githubusercontent.com/7019907/148935122-6bbad4f5-69bb-4fd8-9b47-b2ca7b756bfa.jpg)
![g2](https://user-images.githubusercontent.com/7019907/148935135-6ea4a675-af0a-49d5-9606-fbe8cb05878f.jpg)
![g22](https://user-images.githubusercontent.com/7019907/148935146-dba8bd55-ccf6-41a4-945a-96a58471e785.jpg)
![gg3](https://user-images.githubusercontent.com/7019907/148935151-e428334b-bf90-4035-9637-54efcc4713e2.jpg)

**Comment by jjaychen1e** [comment]
Uninstall the marketplace version, manually reinstall from [releases](https://github.com/JJAYCHEN1e/logseq-plugin-image-uploader/releases).

**Comment by JiangLongLiu** [comment]
> Uninstall the marketplace version, manually reinstall from [releases](https://github.com/JJAYCHEN1e/logseq-plugin-image-uploader/releases).

I tried offline versions 0.0.5 and 0.0.6, and restarted picgo and logseq, but the problem still exists

**Comment by JiangLongLiu** [comment]
> Uninstall the marketplace version, manually reinstall from [releases](https://github.com/JJAYCHEN1e/logseq-plugin-image-uploader/releases).

I tried offline versions 0.0.5 and 0.0.6, and restarted picgo and logseq, but the problem still exists

**Comment by jjaychen1e** [comment]
@JiangLongLiu I test it in 0.5.8, it works for me.
Please check this button:

<img width="389" alt="image" src="https://user-images.githubusercontent.com/31304335/148938584-284c0fcc-253c-4162-b484-53feb7e7d65c.png">

It should show "Reload" instead of "Update" if you install it manually. Only the marketplace version will be forced to use origin "lsp://logseq.io", causing the CORS failure.

**Comment by JiangLongLiu** [comment]
> @JiangLongLiu I test it in 0.5.8, it works for me. Please check this button:
> 
> <img alt="image" width="389" src="https://user-images.githubusercontent.com/31304335/148938584-284c0fcc-253c-4162-b484-53feb7e7d65c.png">
> 
> It should show "Reload" instead of "Update" if you install it manually. Only the marketplace version will be forced to use origin "lsp://logseq.io", causing the CORS failure.

Well, thank you!

However, after I have successfully uploaded pictures in 【A】, I switch to 【B】 and upload them in 【B】, the CORS problem occurs again.

After I reindex 【B】, the problem still exists.

After restarting logseq, the problem did not disappear.

**Comment by JiangLongLiu** [comment]
> 

I found that the problem is bound with the pictures that failed to upload, not with the library.

**Comment by JiangLongLiu** [comment]
> > @JiangLongLiu I test it in 0.5.8, it works for me. Please check this button:
> > <img alt="image" width="389" src="https://user-images.githubusercontent.com/31304335/148938584-284c0fcc-253c-4162-b484-53feb7e7d65c.png">
> > It should show "Reload" instead of "Update" if you install it manually. Only the marketplace version will be forced to use origin "lsp://logseq.io", causing the CORS failure.
> 
> Well, thank you!
> 
> However, after I have successfully uploaded pictures in 【A】, I switch to 【B】 and upload them in 【B】, the CORS problem occurs again.
> 
> After I reindex 【B】, the problem still exists.
> 
> After restarting logseq, the problem did not disappear.

I found that the problem is bound with the pictures that failed to upload, not with the library.
